# -*- mode: ruby -*-
# vi: set ft=ruby :

#use vagrant berkshelf plugin
require 'berkshelf/vagrant'

# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|

  # ubuntu 12.04 LTS box from https://vagrantcloud.com/
  config.vm.box = "hashicorp/precise64"

  config.vm.network :public_network, ip: "192.168.2.222"

  # install latest version of chef onto VM before provisioning
  config.omnibus.chef_version = :latest

  # use Berkschelf to manage cookbook depenencies listed in Berksfile
  config.berkshelf.enabled = true

  config.vm.provision "chef_solo" do |chef|

    # recipes to run
	chef.run_list = %w[
		apt
		wordpress
		logstash::beaver
	]

    # recipe configuration
	chef.json = {

		:mysql => {
			:server_debian_password => "wordpress",
			:server_root_password => "wordpress",
			:server_repl_password => "wordpress"
		},
		
		logstash: {
		  group: 'adm',
		  beaver: {
		    # force specific beaver version via pip
		    pip_package: "git+git://github.com/josegonzalez/beaver.git#egg=beaver",
			# set the logstash_version so beaver starts with master.
			logstash_version:  1,
			server_role: 'server',
			# change to match ip of logstashdemo server
			server_ipaddress: '192.160.2.220',
			# define log files to ship to logstash tagging accordingly
			inputs: [
				{file: {
					type: "syslog",
					tags: ["wordpressdemo", "syslog" ],
					path: ["/var/log/*.log" ]
				}},
				{file: {
					type: "apache-access",
					tags: ["wordpressdemo", "apache-access" ],
					path: ["/var/log/apache2/access.log"]
				}},
				{file: {
					type: "apache-error",
					tags: ["wordpressdemo", "apache-error" ],
					path: ["/var/log/apache2/error.log"]
				}},
				{file: {
					type: "apache-access",
					tags: ["wordpressdemo", "apache-access" ],
					path: ["/var/log/apache2/wordpress-access.log"]
				}},
				{file: {
					type: "apache-error",
					tags: ["wordpressdemo", "apache-error" ],
					path: ["/var/log/apache2/wordpress-error.log"]
				}},				
			],
			
			# ship to redis on 192.168.2.220 - change as needed
			outputs: [
				redis: { 
					host: "192.168.2.220",
					data_type: "list",
					key: "logstash"					
				}
			],	
		  }
		}		
    }

  end
end
