source 'https://api.berkshelf.com'
metadata
cookbook 'java'
cookbook 'logstash', git: 'git://github.com/lusis/chef-logstash.git'
cookbook 'redisio', git: 'git://github.com/brianbianco/redisio.git'
cookbook 'elasticsearch', git: 'git://github.com/elasticsearch/cookbook-elasticsearch.git'
cookbook 'graphite', git: 'https://github.com/hw-cookbooks/graphite.git'
cookbook 'kibana', git: 'https://github.com/lusis/chef-kibana.git'
cookbook 'ufw', git: 'https://github.com/opscode-cookbooks/ufw.git'
